In [3]:
import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv')
df.head()


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(['id', 'Unnamed: 32'], inplace = True, axis = 1)

In [7]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [8]:
X = df.iloc[:, 1:]
y = df.iloc[:, 0]

# Train test split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [10]:
X_train.shape, y_train.shape,  X_test.shape, y_test.shape

((455, 30), (455,), (114, 30), (114,))

# scalling

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train

array([[-0.43711392, -0.03221707, -0.40644936, ..., -0.32589459,
        -1.22618343, -0.69684537],
       [ 0.57004684,  0.53860357,  0.57839454, ...,  0.26007834,
         0.91646005, -0.44371472],
       [-0.50985331, -0.76480874, -0.53178575, ..., -1.00230951,
        -0.65701912, -1.21485288],
       ...,
       [-1.32201655,  0.57095778, -1.30570756, ..., -1.34446906,
        -0.82414216,  0.48834641],
       [ 1.06523421,  1.2180419 ,  0.943452  , ..., -0.00744756,
        -0.62233321, -0.25048969],
       [-0.03984495,  0.09488874, -0.03327951, ...,  1.04289561,
         0.44189369,  1.27769119]])

In [12]:
X_test

array([[ 0.12801517, -1.28247604,  0.09530184, ..., -0.33790285,
        -0.42998405, -0.77906879],
       [-0.40633956, -0.44126668, -0.43362586, ..., -0.88268287,
        -0.33223284, -0.8730384 ],
       [ 0.0272991 ,  1.99685387,  0.02472406, ..., -0.4848901 ,
        -1.59038553, -0.33976083],
       ...,
       [ 0.59802353,  0.61717807,  0.63112506, ..., -0.14273055,
        -0.25655448, -0.24755314],
       [-0.54902067, -0.2725626 , -0.5536892 , ..., -0.86930658,
        -0.77684319, -0.37911061],
       [ 1.21071299,  0.62411112,  1.1462617 , ...,  0.36192059,
         0.33152942, -0.44900051]])

# label encoder

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

y_train

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,

In [14]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1])

# Numpy array to pytorch array

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


In [16]:
X_train_tensor

tensor([[-0.4371, -0.0322, -0.4064,  ..., -0.3259, -1.2262, -0.6968],
        [ 0.5700,  0.5386,  0.5784,  ...,  0.2601,  0.9165, -0.4437],
        [-0.5099, -0.7648, -0.5318,  ..., -1.0023, -0.6570, -1.2149],
        ...,
        [-1.3220,  0.5710, -1.3057,  ..., -1.3445, -0.8241,  0.4883],
        [ 1.0652,  1.2180,  0.9435,  ..., -0.0074, -0.6223, -0.2505],
        [-0.0398,  0.0949, -0.0333,  ...,  1.0429,  0.4419,  1.2777]],
       dtype=torch.float64)

In [17]:
X_test_tensor

tensor([[ 0.1280, -1.2825,  0.0953,  ..., -0.3379, -0.4300, -0.7791],
        [-0.4063, -0.4413, -0.4336,  ..., -0.8827, -0.3322, -0.8730],
        [ 0.0273,  1.9969,  0.0247,  ..., -0.4849, -1.5904, -0.3398],
        ...,
        [ 0.5980,  0.6172,  0.6311,  ..., -0.1427, -0.2566, -0.2476],
        [-0.5490, -0.2726, -0.5537,  ..., -0.8693, -0.7768, -0.3791],
        [ 1.2107,  0.6241,  1.1463,  ...,  0.3619,  0.3315, -0.4490]],
       dtype=torch.float64)

In [18]:
y_train_tensor

tensor([0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,

In [19]:
y_test_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
        1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1],
       dtype=torch.int32)

# Define the model

In [20]:
class MysimpleNN():

  def __init__(self, X):
    self.weight = torch.rand(X.shape[1],1, dtype = torch.float64, requires_grad = True)
    self.baise = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weight) + self.baise
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):

    #clamp predication to avoid log(0)

    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()

    return loss







# Important parameter

In [21]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [22]:
# create model

model  = MysimpleNN(X_train_tensor)

for epoch in range(epochs):

  #forward pass
  y_pred = model.forward(X_train_tensor)

  #calculate loss
  loss = model.loss_function(y_pred, y_train_tensor)

  #backward loss
  loss.backward()

  #parameter update
  with torch.no_grad():
    model.weight -= learning_rate * model.weight.grad
    model.baise -= learning_rate * model.baise.grad

  #zero grad
  model.weight.grad.zero_()
  model.baise.grad.zero_()

  #print loss in each epochs

  print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}')




Epoch: 1, Loss: 3.7682
Epoch: 2, Loss: 3.6442
Epoch: 3, Loss: 3.5167
Epoch: 4, Loss: 3.3828
Epoch: 5, Loss: 3.2487
Epoch: 6, Loss: 3.1124
Epoch: 7, Loss: 2.9697
Epoch: 8, Loss: 2.8278
Epoch: 9, Loss: 2.6828
Epoch: 10, Loss: 2.5306
Epoch: 11, Loss: 2.3753
Epoch: 12, Loss: 2.2172
Epoch: 13, Loss: 2.0595
Epoch: 14, Loss: 1.9040
Epoch: 15, Loss: 1.7491
Epoch: 16, Loss: 1.6044
Epoch: 17, Loss: 1.4710
Epoch: 18, Loss: 1.3462
Epoch: 19, Loss: 1.2350
Epoch: 20, Loss: 1.1406
Epoch: 21, Loss: 1.0632
Epoch: 22, Loss: 1.0016
Epoch: 23, Loss: 0.9539
Epoch: 24, Loss: 0.9177
Epoch: 25, Loss: 0.8904


# Evaluation

In [23]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item():.4f}')

Accuracy: 0.5200
