In [3]:
import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv')
df.head()


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [7]:
df.drop(['id', 'Unnamed: 32'], inplace = True, axis = 1)

In [9]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [14]:
X = df.iloc[:, 1:]
y = df.iloc[:, 0]

# Train test split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [18]:
X_train.shape, y_train.shape,  X_test.shape, y_test.shape

((455, 30), (455,), (114, 30), (114,))

# scalling

In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train

array([[-0.52903964, -0.7888837 , -0.55207613, ..., -1.02441241,
        -0.66507371, -1.16421784],
       [ 1.7828843 ,  0.34651637,  1.840049  , ...,  1.48375097,
         0.2710301 , -0.48613974],
       [ 0.13791539,  0.17941112,  0.09331493, ...,  0.67252981,
         0.19551249, -0.13877907],
       ...,
       [-0.79806352, -0.16853406, -0.79830641, ..., -0.46348082,
         0.24428428, -0.90812658],
       [ 0.21918302,  0.09471394,  0.12414442, ..., -0.88308835,
        -0.40705518, -1.28286808],
       [-0.49260933, -0.53708126, -0.56140611, ..., -1.32286353,
        -1.57915154, -1.36501056]])

In [23]:
X_test

array([[-0.44832749, -0.34661212, -0.38101338, ..., -0.55531707,
        -0.60627523,  0.85009564],
       [ 1.97804931,  0.68037048,  1.93181773, ...,  1.10008994,
        -0.50857654, -0.88803829],
       [ 0.17939188,  0.60021574,  0.18382479, ...,  0.23051817,
         0.24904921, -0.81451205],
       ...,
       [-0.4302202 ,  0.20695655, -0.4269783 , ..., -0.51425396,
        -0.36848029, -0.20643013],
       [-0.26725459,  0.42988692, -0.29085142, ..., -0.72826523,
         0.57348262, -1.08675788],
       [-0.77124082, -1.22831426, -0.80884073, ..., -1.56321517,
        -0.23391416, -1.11921541]])

# label encoder

In [24]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

y_train

array([0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,

In [25]:
y_test

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0])

# Numpy array to pytorch array

In [27]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


In [28]:
X_train_tensor

tensor([[-0.5290, -0.7889, -0.5521,  ..., -1.0244, -0.6651, -1.1642],
        [ 1.7829,  0.3465,  1.8400,  ...,  1.4838,  0.2710, -0.4861],
        [ 0.1379,  0.1794,  0.0933,  ...,  0.6725,  0.1955, -0.1388],
        ...,
        [-0.7981, -0.1685, -0.7983,  ..., -0.4635,  0.2443, -0.9081],
        [ 0.2192,  0.0947,  0.1241,  ..., -0.8831, -0.4071, -1.2829],
        [-0.4926, -0.5371, -0.5614,  ..., -1.3229, -1.5792, -1.3650]],
       dtype=torch.float64)

In [29]:
X_test_tensor

tensor([[-0.4483, -0.3466, -0.3810,  ..., -0.5553, -0.6063,  0.8501],
        [ 1.9780,  0.6804,  1.9318,  ...,  1.1001, -0.5086, -0.8880],
        [ 0.1794,  0.6002,  0.1838,  ...,  0.2305,  0.2490, -0.8145],
        ...,
        [-0.4302,  0.2070, -0.4270,  ..., -0.5143, -0.3685, -0.2064],
        [-0.2673,  0.4299, -0.2909,  ..., -0.7283,  0.5735, -1.0868],
        [-0.7712, -1.2283, -0.8088,  ..., -1.5632, -0.2339, -1.1192]],
       dtype=torch.float64)

In [30]:
y_train_tensor

tensor([0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
        0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,

In [31]:
y_test_tensor

tensor([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0])

# Define the model

In [50]:
class MysimpleNN():

  def __init__(self, X):
    self.weight = torch.rand(X.shape[1],1, dtype = torch.float64, requires_grad = True)
    self.baise = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weight) + self.baise
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):

    #clamp predication to avoid log(0)

    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()

    return loss







# Important parameter

In [61]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [62]:
# create model

model  = MysimpleNN(X_train_tensor)

for epoch in range(epochs):

  #forward pass
  y_pred = model.forward(X_train_tensor)

  #calculate loss
  loss = model.loss_function(y_pred, y_train_tensor)

  #backward loss
  loss.backward()

  #parameter update
  with torch.no_grad():
    model.weight -= learning_rate * model.weight.grad
    model.baise -= learning_rate * model.baise.grad

  #zero grad
  model.weight.grad.zero_()
  model.baise.grad.zero_()

  #print loss in each epochs

  print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}')




Epoch: 1, Loss: 4.1476
Epoch: 2, Loss: 4.0435
Epoch: 3, Loss: 3.9298
Epoch: 4, Loss: 3.8123
Epoch: 5, Loss: 3.6896
Epoch: 6, Loss: 3.5598
Epoch: 7, Loss: 3.4248
Epoch: 8, Loss: 3.2834
Epoch: 9, Loss: 3.1334
Epoch: 10, Loss: 2.9830
Epoch: 11, Loss: 2.8312
Epoch: 12, Loss: 2.6802
Epoch: 13, Loss: 2.5253
Epoch: 14, Loss: 2.3712
Epoch: 15, Loss: 2.2136
Epoch: 16, Loss: 2.0552
Epoch: 17, Loss: 1.8974
Epoch: 18, Loss: 1.7423
Epoch: 19, Loss: 1.5985
Epoch: 20, Loss: 1.4675
Epoch: 21, Loss: 1.3511
Epoch: 22, Loss: 1.2501
Epoch: 23, Loss: 1.1646
Epoch: 24, Loss: 1.0942
Epoch: 25, Loss: 1.0373


# Evaluation

In [67]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item():.4f}')

Accuracy: 0.5065
