In [3]:
import torch

import torch.nn as nn

In [23]:
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, input_features):
        super().__init__()

        # First linear layer
        self.input_to_hidden = nn.Linear(input_features, 3)
        self.activation = nn.ReLU()  # Activation function for non-linearity

        # Second linear layer
        self.hidden_to_output = nn.Linear(3, 1)
        self.output_activation = nn.Sigmoid()  # Sigmoid for binary classification

    def forward(self, input_features):

        hidden_output = self.input_to_hidden(input_features)
        hidden_output = self.activation(hidden_output)

        output = self.hidden_to_output(hidden_output)
        output = self.output_activation(output)

        return output


In [24]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call the model for forward pass
#model.foward(features)

model(features)

tensor([[0.5261],
        [0.5261],
        [0.5261],
        [0.5261],
        [0.5261],
        [0.5261],
        [0.5261],
        [0.5261],
        [0.5261],
        [0.5261]], grad_fn=<SigmoidBackward0>)

In [25]:
# showing model weights
model.input_to_hidden.weight

Parameter containing:
tensor([[-0.1754,  0.0860, -0.1800, -0.2658,  0.1496],
        [-0.3434, -0.3819, -0.2036, -0.2514, -0.3455],
        [-0.2438,  0.0623, -0.3888,  0.1252, -0.3522]], requires_grad=True)

In [26]:
# showing model biase
model.input_to_hidden.bias

Parameter containing:
tensor([ 0.1285, -0.0259, -0.2948], requires_grad=True)

In [15]:
!pip install torchinfo

In [27]:
from torchinfo import summary

summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential container

In [31]:
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, input_features):
        super().__init__()

        self.network = nn.Sequential(
              nn.Linear(input_features, 3),
              nn.ReLU()  ,
              nn.Linear(3, 1),
              nn.Sigmoid() ,
        )

    def forward(self, input_features):

      out = self.network(input_features)

      return out




In [36]:
# create dataset

features  = torch.rand(10,5)

features.shape[1]


5

In [37]:
model = Model(features.shape[1])
model.forward(features)

tensor([[0.4057],
        [0.4048],
        [0.4056],
        [0.4030],
        [0.4052],
        [0.4051],
        [0.4053],
        [0.4052],
        [0.4058],
        [0.3908]], grad_fn=<SigmoidBackward0>)