In [ ]:
import torch

In [ ]:
torch.__version__

'2.5.1+cu121'

In [ ]:
if torch.cuda.is_available():
    print('CUDA is available')
    print("Device Name:", torch.cuda.get_device_name(0))
else:
    print('CUDA is not available')

CUDA is available
Device Name: Tesla T4


# Create Torch

In [ ]:
# empty
a = torch.empty((2,3), dtype=torch.float32)

In [ ]:
#type
type(a)

torch.Tensor

In [ ]:
#using zero
torch.zeros((2,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# using one
torch.ones((2,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#using rand

torch.rand((2,3))

tensor([[0.1990, 0.8459, 0.5265],
        [0.1925, 0.0028, 0.8528]])

In [ ]:
# using manual seed
torch.manual_seed(42)
torch.rand((2,3))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
#other way

print("using arange-> ",torch.arange(0,10,2))

print("using linspace-> ",torch.linspace(0,10,2))

print("using eye-> ",torch.eye(3))

print("using full-> ",torch.full((2,3), 3))


using arange->  tensor([0, 2, 4, 6, 8])
using linspace->  tensor([ 0., 10.])
using eye->  tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using full->  tensor([[3, 3, 3],
        [3, 3, 3]])


# Tensor shape

In [ ]:
x = torch.tensor([[1,2,3], [3,4,5]])
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
print(torch.empty_like(x))

tensor([[    140109417586064,     140109417586064,                   0],
        [                  0,                   0, 7310593858020254331]])


In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

# Tensor Data type

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
torch.tensor([[1,2,3], [2,3,4]], dtype = torch.float)

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [ ]:
# usgin to()

x.to(torch.float16)

tensor([[1., 2., 3.],
        [3., 4., 5.]], dtype=torch.float16)

# mathimatical operation

In [ ]:
x = torch.rand((2,4))
x

tensor([[0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414]])

In [ ]:
# addition
x + 2

# subtraction
x - 2

# multiplication
x * 2

# division
x / 2

# int divsion
(x *100) //2

# mod
((x *100) //2) % 2
# power

x**2



tensor([[0.5492, 0.1844, 0.7840, 0.3294],
        [0.0711, 0.3937, 0.0727, 0.1948]])

In [ ]:
c = torch.tensor(([3,4,5], [4,5,6]))
c

tensor([[3, 4, 5],
        [4, 5, 6]])

In [ ]:
# absolute value
torch.abs(c)

tensor([[3, 4, 5],
        [4, 5, 6]])

In [ ]:
# negative
torch.neg(c)

tensor([[-3, -4, -5],
        [-4, -5, -6]])

In [ ]:
# round

d = torch.tensor(([2.99,3.99,4], [43,4,5]))
torch.round(d)

tensor([[ 3.,  4.,  4.],
        [43.,  4.,  5.]])

In [ ]:
# ceil
torch.ceil(d)



tensor([[ 3.,  4.,  4.],
        [43.,  4.,  5.]])

In [ ]:
# floar
torch.floor(d)

tensor([[ 2.,  3.,  4.],
        [43.,  4.,  5.]])

In [ ]:
# clamp

torch.clamp(d, min = 2, max = 4)

tensor([[2.9900, 3.9900, 4.0000],
        [4.0000, 4.0000, 4.0000]])

# Reduction operation


In [ ]:
e = torch.randint( size = (2,4), low = 0, high = 10)
e

tensor([[2, 0, 5, 9],
        [3, 4, 9, 6]])

In [ ]:
sum = torch.sum(e)

# sum along column
sum = torch.sum(  e, dim = 0)
print("sum along column:", sum)

# sum along row
sum = torch.sum(  e, dim = 1)
# sum along row
print("sum along row:", sum)




sum along column: tensor([ 5,  4, 14, 15])
sum along row: tensor([16, 22])


In [ ]:
import torch
d = torch.tensor([2,3,4], dtype = float)

# mean
torch.mean(d)

tensor(3., dtype=torch.float64)

In [ ]:
# matrix multiplication
a = torch.tensor([23,4,5])
b = torch.tensor([3,4,5])

torch.matmul(a,b)

tensor(110)

In [ ]:
# dot product

torch.dot(a,b)


tensor(110)

In [ ]:
# determinit
h = torch.randint(size = (2,2), low = 0, high = 10, dtype = torch.float64)

torch.det(h)

tensor(42., dtype=torch.float64)

In [ ]:
# inverse

torch.inverse(h)

tensor([[ 0.1429,  0.0000],
        [-0.1905,  0.1667]], dtype=torch.float64)

# special function


In [ ]:
# exp
torch.exp(d)

tensor([ 7.3891, 20.0855, 54.5982], dtype=torch.float64)

In [ ]:
#sqrt

torch.sqrt(d)

tensor([1.4142, 1.7321, 2.0000], dtype=torch.float64)

In [ ]:
# sigmoid

torch.sigmoid(d)

tensor([0.8808, 0.9526, 0.9820], dtype=torch.float64)

In [ ]:
# softmax

# the dtype should be float.

torch.softmax(d, dim = 0)

tensor([0.0900, 0.2447, 0.6652], dtype=torch.float64)

In [ ]:
# relu

torch.relu(d)

tensor([2., 3., 4.], dtype=torch.float64)